apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-express-app-aryas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app   # Ensure this matches the labels in the pod template
  template:
    metadata:
      labels:
        app: nodejs-app   # Ensure this matches the labels in the selector
    spec:
      containers:
      - name: my-express-app-container
        image: my-express-app-aryas:v1
        ports:
        - containerPort: 3000
